# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# https://pre-commit.com/#pre-commit-configyaml---top-level
fail_fast: true
repos:
-   repo: https://gitlab.com/PyCQA/flake8
    rev: '3.8.4'
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.790'
    hooks:
    -   id: mypy
        # https://pre-commit.com/#pre-commit-configyaml---hooks
        verbose: true
